Web/ViewModels/HomeViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels
{
    public class HomeViewModel
    {
        public Owner Owner { get; set; }
        public List<Portfolio> Portfolios { get; set; }
        public List<ProtfolioImage> ProtfolioImages { get; set; }


    }
}

Web/Controllers/HomeController.cs
using Core.Entities;
using Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;
using Web.Services;
using Web.ViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork<Owner> _owner;
        private readonly IUnitOfWork<Portfolio> _portfolio;
        private readonly IUnitOfWork<ProtfolioImage> _portfolioImage;

        public HomeController(IUnitOfWork<Owner> owner,
                              IUnitOfWork<Portfolio> portfolio,
                              IUnitOfWork<ProtfolioImage> portfolioImage)
        {
            _owner = owner;
            _portfolio = portfolio;
            _portfolioImage = portfolioImage;
        }
        public IActionResult Index()
        {
            
            var homeViewModel = new HomeViewModel
            {
                Owner = _owner.Entity.GetAll().First(),
                Portfolios = _portfolio.Entity.GetAll().ToList(),
                ProtfolioImages = _portfolioImage.Entity.GetAll().ToList()
            };

            return View(homeViewModel);
            
         
           //return View();
        }

        /*
        private readonly ILogger<HomeController> _logger;
        private readonly IPortfolioService _iPortfolioService;

        public HomeController(ILogger<HomeController> logger, IPortfolioService portfolioService)
        {
            _logger = logger;
            _iPortfolioService = portfolioService;
       
        }

        public async Task<IActionResult> IndexAsync()
        {
           // _iPortfolioService.GetAllAsync();
          

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        */

    }
}

Web/Controllers/PortfolioController.cs
using Core.Entities;
using Core.Interfaces;
using Infrastructure;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;
using Web.Services;
using Web.ViewModels;

namespace Web.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly DataContext _context;
        private readonly IUnitOfWork<Portfolio> _portfolio;
        private readonly IUnitOfWork<ProtfolioImage> _portfolioImage;
        private readonly IHostingEnvironment _hosting;

        public PortfolioController(DataContext context,  IUnitOfWork<Portfolio> portfolio, IUnitOfWork<ProtfolioImage> portfolioImage, IHostingEnvironment hosting)
        {
            _context = context;
            _portfolio = portfolio;
            _portfolioImage = portfolioImage;
            _hosting = hosting;
        }

        public IActionResult Index()
        {

            var portfolioViewModel = new PortfolioViewModel
            {            
                Portfolios = _portfolio.Entity.GetAll().ToList(),
               //ProtfolioImages = _portfolioImage.Entity.GetAll().ToList()
            };

            return View(portfolioViewModel);


            
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioViewModel = new PortfolioViewModel
            {

                Portfolio = _context.Portfolios.Include(x=>x.ProtfolioImages)
                            .FirstOrDefault(x => x.Id == id)
            };

            return View(portfolioViewModel);
            
         
           
        }

        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PortfolioViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.LogoImage != null)
                {
                    string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                    string logoPath = Path.Combine(uploads, model.LogoImage.FileName);
                    string imagePath = Path.Combine(uploads, model.ImageFile.FileName);
                    model.LogoImage.CopyTo(new FileStream(logoPath, FileMode.Create));
                    model.ImageFile.CopyTo(new FileStream(imagePath, FileMode.Create));
                }

                Portfolio portfolioItem = new Portfolio
                {
                    ProjectName = model.ProjectName,
                    Description = model.Description,
                    LogoUrl = model.LogoImage.FileName,
                };

                ProtfolioImage protfolioImage = new ProtfolioImage
                {
                    Description = "",
                    ImageUrl = model.ImageFile.FileName,
                };

                portfolioItem.ProtfolioImages.Add(protfolioImage);

                _portfolio.Entity.Insert(portfolioItem);
                //_portfolioImage.Entity.Insert(protfolioImage);
                _portfolio.Save();
                //_portfolioImage.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: PortfolioItems/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var portfolioItem = _portfolio.Entity.GetById(id);
            //var ProtfolioImages = _portfolioImage.Entity.GetAll().Where(x => x.Portfolio.Id == id).ToList();
            //var PortfolioImages = _portfolioImage.Entity.GetAll().ToList();

            
             var portfolioItem  = _context.Portfolios.Include(x=>x.ProtfolioImages)
                            .FirstOrDefault(x => x.Id == id);
            var PortfolioImages = portfolioItem.ProtfolioImages.ToList();
           


            if (portfolioItem == null)
            {
                return NotFound();
            }

             var portfolioViewModel = new PortfolioViewModel
            {

                Id = portfolioItem.Id,
                ProjectName = portfolioItem.ProjectName,
                Description = portfolioItem.Description,
                LogoUrl = portfolioItem.LogoUrl,
                protfolioImages = PortfolioImages
                
            };

           

            return View(portfolioViewModel);
        }

        // POST: PortfolioItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, PortfolioViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.LogoImage != null || model.ImageFile != null)
                    {
                        string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                        string logoPath = Path.Combine(uploads, model.LogoImage.FileName);
                        string imagePath = Path.Combine(uploads, model.ImageFile.FileName);
                        model.LogoImage.CopyTo(new FileStream(logoPath, FileMode.Create));
                        model.ImageFile.CopyTo(new FileStream(imagePath, FileMode.Create));
                    }


                    //var portfolioItem = _context.Portfolios.Include(x => x.ProtfolioImages)
                    //        .FirstOrDefault(x => x.Id == id);
                    //var PortfolioImages = portfolioItem.ProtfolioImages.ToList();
                    //var portfolioImagesIds = PortfolioImages.Select(x => x.Id).ToList();
                    //if (portfolioImagesIds.Count != 0)
                    //{
                    //    foreach (var item in portfolioImagesIds)
                    //    {
                    //        _portfolioImage.Entity.Delete(item);
                    //        _portfolio.Save();
                    //    }

                    //}

                    ProtfolioImage protfolioImage = new ProtfolioImage
                    {

                        Description = "",
                        ImageUrl = model.ImageFile.FileName,
                    };


                    Portfolio portfolioItem = new Portfolio
                    {
                        Id = model.Id,
                        ProjectName = model.ProjectName,
                        Description = model.Description,
                        LogoUrl = model.LogoImage.FileName,
                                               
                        
                    };


                    portfolioItem.ProtfolioImages.Add(protfolioImage);
                    

                    _portfolio.Entity.Update(portfolioItem);
                    //_portfolioImage.Entity.Update(protfolioImage);
                    
                    //_portfolioImage.Save();
                    _portfolio.Save();


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioItemExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

       
        // GET: PortfolioItems/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var portfolioViewModel = new PortfolioViewModel
            {
                Portfolio = _context.Portfolios.Include(x => x.ProtfolioImages)
                            .FirstOrDefault(x => x.Id == id)
                //Portfolio = _portfolio.Entity.GetAll().FirstOrDefault(x => x.Id == id),
            };

            return View(portfolioViewModel);
           
        }

        // POST: PortfolioItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            
                  
            _portfolio.Entity.Delete(id);
            _portfolio.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioItemExists(int id)
        {
            return _portfolio.Entity.GetAll().Any(e => e.Id == id);
        }
    }


}

Web/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Index";
}


<!-- Masthead -->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Avatar Image -->
        <img class="masthead-avatar mb-5" src="~/img/@Model.Owner.Avatar" style="border-radius:50%" alt="">


        <!-- Masthead Heading -->
        <h1 class="masthead-heading text-uppercase mb-0">@Model.Owner.FullName</h1>


        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Masthead Subheading -->
        <p class="masthead-subheading font-weight-light mb-0">@Model.Owner.profil<br> We make apps and games on all platforms including social networking platforms.<br> Some of our apps, games and software solutions are provided below.<br> For more details please contact us.</p>

    </div>
</header>

<!-- Portfolio Section -->
<section class="page-section portfolio" id="portfolio">
    <div class="container">

        <!-- Portfolio Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Portfolio</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Portfolio Grid Items -->
        <div class="row">

            <!--Portfolio-->
            @foreach (var portfolioItem in Model.Portfolios)
            {
          

           
                <div class="col-md-6 col-lg-3 mb-3 mb-md-4 mb-lg-0">
                    <div class="portfolio-item mx-auto">
                        <div class="card h-100 hover-box-shadow">
                            <a href="@Url.Action("Details", "Portfolio", new { id = portfolioItem.Id })">
                                <div class="d-block bg-gradient rounded-top position-relative">
                                    <img class="card-img-top hover-fade-out" src="~/img/portfolio/@portfolioItem.LogoUrl" alt="Image accompanying Circle testimonial">
                                </div>

                                <div class="card-body">
                                    <h3>@portfolioItem.ProjectName</h3>
                                    <p>
                                        for more information please click here!
                                    </p>

                                </div>
                            </a>
                        </div>
                    </div>
                </div>
           


            }



        </div>
        <!-- /.row -->

    </div>
</section>


<!-- projects & experience Section -->
<section class="pb-5 pt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card card-body shadow-sm h-100">
                    <h1><mark data-aos="highlight-text" data-aos-delay="500" class="aos-init aos-animate">Projects</mark></h1>
                    <div class="display-4 text-primary mb-3" data-countup="" data-start="" data-end="60" data-duration="" data-decimal-places="" data-prefix="" data-separator="." data-grouping="true" data-suffix=" bn €" data-easing="">60 bn €</div>
                    <div>
                        Off-market volume of 60 billion euros p.a.
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card card-body shadow-sm h-100">
                    <h1><mark data-aos="highlight-text" data-aos-delay="500" class="aos-init aos-animate">Experience</mark></h1>

                    <div class="display-4 text-primary mb-3" data-countup="" data-start="0" data-end="98" data-duration="1" data-decimal-places="" data-prefix="" data-separator="" data-grouping="" data-suffix=" %" data-easing="false">98 %</div>
                    <div>of professional market actors regularly pursue off-market transactions</div>
                </div>

            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card card-body shadow-sm h-100">
                    <h1><mark data-aos="highlight-text" data-aos-delay="500" class="aos-init aos-animate">Success rate</mark></h1>
                    <div class="display-4 text-primary mb-3" data-countup="" data-start="1" data-end="75" data-duration="" data-decimal-places="" data-prefix="" data-separator="" data-grouping="" data-suffix="%" data-easing="">75%</div>
                    <div>
                        For three quarters of all sellers and two thirds of all buyers at least every second off-market transaction is successful.
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- About Section -->
<section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">

        <!-- About Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>

        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- About Section Content -->
        <div class="row">
            <div class="col-lg-4 mr-auto">
                <p class="lead">
                    Research Works<hr>
                    Connection Space
                    <br>This is a research project with a huge vision in mind with connection space AI and next generation UI techniques for any digital system to solve a given problem based on previous data and future projection. This research will try to prove my favorite quote "Everything is Connected."
                </p>
            </div>

            <div class="col-lg-4 ml-auto text-center">
                <p class="lead">Asif Hossain Shantu<br />Software Engineer<br />M.Sc. in Applied Computer Science<br />Technical University of Kaiserslautern, Germany</p>
            </div>

            <div class="col-lg-4 mr-auto">
                <p class="lead">
                    Vision<hr>
                    Implementation of new Ideas from us for us for our future.
                    <br>Solve daily life problem with latest technologies. Applying best practices of software development techniques, maintain great quality, high security and better user experience.Regards,
                </p>
            </div>
        </div>

        <!-- About Section Button -->
        <div class="text-center mt-4">
            <a class="btn btn-xl btn-outline-light" href="https://www.xing.com/profile/AsifHossain_Shantu">
                <i class="fab fa-fw fa-xing mr-2"></i>
                Xing Profile
            </a>
            <a class="btn btn-xl btn-outline-light" href="https://www.facebook.com/ShantuApps">
                <i class="fab fa-fw fa-facebook-f mr-2 "></i>
                Facebook Page
            </a>

        </div>

    </div>
</section>

<!-- Contact Section -->
<section class="page-section" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <form name="sentMessage" id="contactForm" novalidate="novalidate">
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Name</label>
                            <input class="form-control" id="name" type="text" placeholder="Name" required="required" data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Email Address</label>
                            <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Phone Number</label>
                            <input class="form-control" id="phone" type="tel" placeholder="Phone Number" required="required" data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Message</label>
                            <textarea class="form-control" id="message" rows="5" placeholder="Message" required="required" data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Send</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</section>



<!-- Portfolio Modals -->
<!-- Portfolio Modal 1 -->


@foreach (var item in Model.Portfolios)
{
  

    <div class="portfolio-modal modal fade" id="item-@item.Id" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
                <div class="modal-body text-center">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <!-- Portfolio Modal - Title -->
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@item.ProjectName</h2>
                                <!-- Icon Divider -->
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon">
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                @foreach (var ProtfolioImage in Model.ProtfolioImages)
                                {
                                
                                    <!-- Portfolio Modal - Image -->
                                    <img class="img-fluid rounded mb-5" src="~/img/portfolio/@ProtfolioImage.ImageUrl" alt="">

                                 }
                                <!-- Portfolio Modal - Text -->
                                <p class="mb-5">
                                    @item.Description
                                </p>
                                <button class="btn btn-primary" href="#" data-dismiss="modal">
                                    <i class="fas fa-times fa-fw"></i>
                                    Close Window
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}